networks:
  kanban-net:
    driver: bridge

services:
  web:
    image: node:20.17-alpine3.19
    networks:
      - kanban-net
    ports:
      - 5173:5173
    volumes:
      - ./:/app/
    working_dir: /app
    command: npm run dev
    depends_on: 
      - server
  server:
    image: node:20.17-alpine3.19
    environment:
      - DATABASE_URL=postgresql://kanban_user:kanban_password@postgres:5432/kanban_board_db?schema=public
    networks:
      - kanban-net
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src/
      - ./node_modules:/app/node_modules
      - ./prisma:/app/prisma/
    working_dir: /app
    command:  npx nodemon /app/src/server/main.mjs
    depends_on: 
      - postgres
  postgres:
    image: postgres:17-alpine
    networks:
      - kanban-net
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=kanban_password
      - POSTGRES_USER=kanban_user
      - POSTGRES_DB=kanban_board_db
